stages:
  - deploy

cache:
  paths:
    - node_modules/

services:
  - docker:dind

deploy:
  stage: deploy
  script:
    - docker rm -f assets
    - docker build -t assets .
    - docker run -d --rm --name assets -p 3000:3000 assets
    - docker image prune -f

  runs-on: self-hosted

  only:
    - main
