on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          docker rm -f dayat
          docker build -t dayat .

      - name: Deploy and Running project
        run: |
          docker run -d --rm --name dayat -p 3001:3000 dayat
          docker image prune -f
