on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          sudo docker rm -f dayat-wedding
          sudo docker build -t dayat-wedding .

      - name: Deploy and Running project
        run: |
          sudo docker run -d --rm --name dayat-wedding -p 3001:3000 dayat-wedding
